plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.antai'
    compileSdk 35

    defaultConfig {
        applicationId 'com.antai'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '1.3.0'
    }

    buildFeatures {
        compose true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    composeOptions {
        kotlinCompilerExtensionVersion '1.5.14'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation 'androidx.activity:activity-compose:1.9.0'
    implementation 'androidx.compose.material3:material3:1.2.1'
    implementation 'androidx.compose.foundation:foundation:1.6.8'
}
